- name: understand facts
  hosts: centos:ubuntu #all created 2 instances with keypair-devops. ref:devopsbook-5
  become: yes
  tasks:
  - name: print all the facts #prints all the variables in execution
    ansible.builtin.debug:
      msg: "All facts: {{ansible_facts}}"
  
  # just imagine we don't have any user id module available, only for practice 
  - name: add user for CentOS
    ansible.builtin.command: user add honey
    when: ansible_facts['distribution'] == "CentOS"

  - name: add user Ubntu
    ansible.builtin.command: add user honey
    when: ansible_facts['distribution'] == "Ubuntu"