- name: installing roboshop project
  hosts: mongodb
  become: yes
  tasks:
  - name: print the variables according to environment
    ansible.builtin.debug:
      msg: "Hello {{NAME}}" #name is variable 