- name: DEMO filters
  hosts: localhost
  vars:
    NAME: Harika
  tasks:
  - name: convert into Upper Case
    debug:
      msg: "{{ NAME | upper }}"

  - name: convert into Upper Case
    debug:
      msg: "{{ NAME | lower }}"

  - name: printing undefined variable
    debug:
      msg: "{{ COURSE | default("DevOps") }}"