- name: DEMO filters # filters module "{{ variable | filtertype }}"
  hosts: localhost
  vars:
    NAME: Harika #Upper case,Lower case
    website: https://www.joindevops.com/batch-74s #URL
    Greeting: Hello Apple,how are you #String
  tasks:
  - name: convert into Upper Case
    debug:
      msg: "{{ NAME | upper }}" 

  - name: convert into Upper Case
    debug:
      msg: "{{ NAME | lower }}"

  - name: printing undefined variable   
    debug:
      msg: "{{ COURSE | default('DevOps') }}"  # if user forgets to give variables in command line..so user has an option

  - name: extract hostname #add variable website:url, we need only hostname--joindevops.com so we split
    debug:
      msg: "{{ website | urlsplit('hostname') }}"

  - name: split string
    debug:
      #msg: "{{ Greeting | join (' ') }}" #joining List to String
      msg: "{{ Greeting | split(',') }}" #splitting String into List 
